# Generated by Django 5.2.1 on 2025-05-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_request_region_id_request_sector'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='listing',
            name='unique_listing_type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
    ]
