# Generated by Django 5.2.1 on 2025-05-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingimage',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='url',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='imagini_anunturi/'),
            preserve_default=False,
        ),
    ]
