# Generated by Django 5.2.1 on 2025-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_listingimage_is_main_remove_listingimage_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='estimated_price',
            field=models.IntegerField(default=0),
        ),
    ]
