# Generated by Django 5.2.1 on 2025-05-23 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_request_estimated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apartments', to='api.condition'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='construction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apartments', to='api.constructiontype'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='apartment', to='api.listing'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='planning_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apartments', to='api.planningtype'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commercial_spaces', to='api.condition'),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='commercial_space', to='api.listing'),
        ),
        migrations.AlterField(
            model_name='house',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='house', to='api.listing'),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_surface',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='land',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='land', to='api.listing'),
        ),
        migrations.AlterField(
            model_name='land',
            name='surface_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lands', to='api.surfacetype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='api.location'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='api.propertytype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='api.saletype'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='api.sector'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='images', to='api.listing'),
        ),
    ]
