# Generated by Django 5.2.1 on 2025-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_apartment_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
