# Generated by Django 5.2.1 on 2025-05-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_listing_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
    ]
