# Generated by Django 5.2.1 on 2025-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_apartment_rooms_alter_apartment_surface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='surface',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commercialspace',
            name='surface',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='house',
            name='surface',
            field=models.IntegerField(),
        ),
    ]
